services:

  celery-worker:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    command: celery -A celery_app.celery worker --loglevel=info
    volumes:
      - ./flask_app:/app
    env_file:
      - ./flask_app/.env
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    working_dir: /app
    depends_on:
      - redis
      - flask-backend

  celery-beat:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    command: celery -A celery_app.celery beat --loglevel=info
    volumes:
      - ./flask_app:/app
    env_file:
      - ./flask_app/.env
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    working_dir: /app
    depends_on:
      - redis
      - flask-backend

  redis:
    image: redis:latest
    container_name: "redis_db"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

  flask-backend:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./flask_app/logs:/app/logs
    env_file:
      - ./flask_app/.env
    environment:
      - FLASK_ENV=production
    depends_on:
      - redis

  telegram-bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    volumes:
      - ./bot:/app
      - ./bot/logs:/app/logs
    env_file:
      - ./bot/.env
    environment:
      - ENV_TYPE=production
    depends_on:
      - flask-backend
      - nginx

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - flask-backend

volumes:
  redis_data:
