services:

  flask-backend:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./flask_app:/app
      - ./flask_app/logs:/app/logs
    env_file:
      - ./flask_app/.env


  telegram-bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    volumes:
      - ./bot:/app
      - ./bot/logs:/app/logs
    env_file:
      - ./bot/.env
    depends_on:
      - flask-backend
      - nginx

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - flask-backend