version: "3.9"

services:
  react-frontend:
    build:
      context: ./react_frontend
      dockerfile: Dockerfile.dev  # Only for development
    ports:
      - "3000:3000"
    volumes:
      - ./react_frontend:/app
      - ./react_frontend/logs:/app/logs
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./react_frontend/.env
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  flask-backend:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./flask_app:/app
      - ./flask_app/logs:/app/logs
    env_file:
      - ./flask_app/.env
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  telegram-bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    volumes:
      - ./bot:/app
      - ./bot/logs:/app/logs
    env_file:
      - ./bot/.env
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
  logging:
    options:
      max-size: "10m"
      max-file: "5"
    depends_on:
      - react-frontend
      - flask-backend